"""Versioned canonical public-contract targets covered by built-in knowledge.

This registry is intentionally independent of every knowledge-pack payload.
Pack loading compares a coverage manifest with this fixed public contract; it
must never infer the expected surface from the pack currently being checked.
"""
from __future__ import annotations


SUPPORTED_TARGET_REGISTRY_VERSION = "hlsgraph.knowledge_supported_targets.v1"


CANONICAL_SUPPORTED_TARGETS: dict[str, frozenset[tuple[str, str]]] = {
    "hlsgraph.supported_amd_2024_2_contract_surface": frozenset({
        ("artifact_kind", "amd.vitis.cosim_report"),
        ("artifact_kind", "amd.vitis.cosim_rpt"),
        ("artifact_kind", "amd.vitis.csim_result"),
        ("artifact_kind", "amd.vitis.csynth_xml"),
        ("artifact_kind", "amd.vitis.dataflow_profile"),
        ("artifact_kind", "amd.vitis.directive_status"),
        ("artifact_kind", "amd.vitis.schedule_json"),
        ("artifact_kind", "amd.vivado.physical_summary"),
        ("artifact_kind", "amd.vivado.post_route_timing"),
        ("artifact_kind", "amd.vivado.post_route_utilization"),
        ("artifact_kind", "amd.vivado.qor_summary"),
        ("artifact_kind", "amd.vivado.routed_checkpoint"),
        ("artifact_kind", "amd.vivado.timing_summary"),
        ("artifact_kind", "amd.vivado.utilization"),
        ("artifact_kind", "constraint.xdc"),
        ("diagnostic_code", "gate.resource_capacity_incomplete"),
        ("diagnostic_code", "gate.resource_capacity_unknown"),
        ("diagnostic_code", "mapping.ambiguous_report_scope"),
        ("diagnostic_code", "mapping.unresolved_report_scope"),
        ("diagnostic_code", "verification.missing_workload"),
        ("diagnostic_code", "vitis.report_parse_error"),
        ("diagnostic_code", "vivado.report_parse_error"),
        ("directive_kind", "ARRAY_PARTITION"),
        ("directive_kind", "DATAFLOW"),
        ("directive_kind", "DEPENDENCE"),
        ("directive_kind", "INLINE"),
        ("directive_kind", "INTERFACE"),
        ("directive_kind", "LOOP_TRIPCOUNT"),
        ("directive_kind", "PIPELINE"),
        ("directive_kind", "STREAM"),
        ("directive_kind", "UNROLL"),
        ("gate_kind", "correctness"),
        ("gate_kind", "post_route_timing"),
        ("gate_kind", "resource_fits"),
        ("predicate", "clock.estimated_period_ns"),
        ("predicate", "clock.requested_period_ns"),
        ("predicate", "cosim.interval_avg_cycles"),
        ("predicate", "cosim.interval_max_cycles"),
        ("predicate", "cosim.interval_min_cycles"),
        ("predicate", "cosim.latency_avg_cycles"),
        ("predicate", "cosim.latency_max_cycles"),
        ("predicate", "cosim.latency_min_cycles"),
        ("predicate", "cosim.status"),
        ("predicate", "csim.assertions_failed"),
        ("predicate", "csim.exit_code"),
        ("predicate", "csim.mismatches"),
        ("predicate", "directive.achieved"),
        ("predicate", "directive.declared_selected"),
        ("predicate", "directive.reported_requested"),
        ("predicate", "directive.requested"),
        ("predicate", "directive.tool_effective"),
        ("predicate", "directive.tool_status"),
        ("predicate", "physical.cdc_critical"),
        ("predicate", "physical.congestion_level"),
        ("predicate", "physical.drc_errors"),
        ("predicate", "physical.slr_crossings"),
        ("predicate", "power.dynamic_w"),
        ("predicate", "power.static_w"),
        ("predicate", "profile.fifo_max_occupancy"),
        ("predicate", "profile.read_block_cycles"),
        ("predicate", "profile.token_count"),
        ("predicate", "profile.write_block_cycles"),
        ("predicate", "qor.achieved_ii"),
        ("predicate", "qor.interval_max_cycles"),
        ("predicate", "qor.interval_min_cycles"),
        ("predicate", "qor.iteration_latency_cycles"),
        ("predicate", "qor.latency_best_cycles"),
        ("predicate", "qor.latency_cycles"),
        ("predicate", "qor.latency_worst_cycles"),
        ("predicate", "qor.pipeline_depth"),
        ("predicate", "qor.target_ii"),
        ("predicate", "qor.trip_count"),
        ("predicate", "resource.available_bram_18k"),
        ("predicate", "resource.available_dsp"),
        ("predicate", "resource.available_ff"),
        ("predicate", "resource.available_lut"),
        ("predicate", "resource.available_uram"),
        ("predicate", "resource.bram_18k"),
        ("predicate", "resource.dsp"),
        ("predicate", "resource.ff"),
        ("predicate", "resource.lut"),
        ("predicate", "resource.uram"),
        ("predicate", "schedule.end_cycle"),
        ("predicate", "schedule.operation_latency"),
        ("predicate", "schedule.pipeline_stage"),
        ("predicate", "schedule.start_cycle"),
        ("predicate", "timing.critical_path_delay_ns"),
        ("predicate", "timing.tns_ns"),
        ("predicate", "timing.wns_ns"),
    }),
    "hlsgraph.supported_axi_contract_surface": frozenset({
        ("directive_kind", "INTERFACE"),
        ("entity_kind", "hls.port"),
        ("entity_kind", "hls.stream"),
        ("relation_kind", "hls.streams_to"),
    }),
    "hlsgraph.supported_open_ir_contract_surface": frozenset({
        ("diagnostic_code", "llvm.bitcode_requires_plugin"),
        ("diagnostic_code", "llvm.instruction_limit"),
        ("diagnostic_code", "mapping.ambiguous_mlir_location"),
        ("diagnostic_code", "mapping.unresolved_mlir_location"),
        ("diagnostic_code", "mlir.experimental_text_parser"),
        ("diagnostic_code", "mlir.operation_limit"),
        ("diagnostic_code", "mlir.unsupported_dialect"),
        ("entity_kind", "hls.buffer"),
        ("entity_kind", "hls.process"),
        ("entity_kind", "ir.llvm.block"),
        ("entity_kind", "ir.llvm.function"),
        ("entity_kind", "ir.llvm.module"),
        ("entity_kind", "ir.llvm.operation"),
        ("entity_kind", "ir.mlir.function"),
        ("entity_kind", "ir.mlir.module"),
        ("entity_kind", "ir.mlir.operation"),
        ("hlsgraph.plugin_contract", "dynamatic.adapter"),
        ("hlsgraph.plugin_contract", "scalehls.adapter"),
        ("predicate", "feature.bitwidth"),
        ("predicate", "feature.debug_location"),
        ("predicate", "feature.dependence_distance"),
        ("predicate", "feature.index_histogram"),
        ("predicate", "feature.loop_bounds"),
        ("predicate", "feature.memory_access"),
        ("predicate", "feature.operation_histogram"),
        ("predicate", "feature.software_call_targets"),
        ("predicate", "feature.trip_count"),
        ("relation_kind", "cross.maps_to"),
        ("relation_kind", "cross.projects_to"),
        ("relation_kind", "handshake.dataflow"),
        ("relation_kind", "hls.streams_to"),
        ("relation_kind", "ir.contains"),
        ("relation_kind", "ir.ssa_use"),
        ("relation_kind", "llvm.calls"),
        ("relation_kind", "llvm.cfg"),
    }),
}


def canonical_supported_targets(
    coverage_scope: str, registry_version: str,
) -> frozenset[tuple[str, str]]:
    """Return the immutable expected target set or fail for an unknown contract."""

    if registry_version != SUPPORTED_TARGET_REGISTRY_VERSION:
        raise KeyError(f"unsupported target registry version: {registry_version!r}")
    try:
        return CANONICAL_SUPPORTED_TARGETS[coverage_scope]
    except KeyError as exc:
        raise KeyError(f"unknown canonical coverage scope: {coverage_scope!r}") from exc
